"use strict";
exports.__esModule = true;
var Exercise2_1 = require("./Exercise/Exercise2");
Exercise2_1["default"].question1();
Exercise2_1["default"].question2();
Exercise2_1["default"].question3();
// Exercise3.question1();
// Exercise4.question1();
// Exercise4.question2();
// Exercise4.question3();
// Exercise4.question4();
// Exercise5.question1();
// Exercise5.question2();
// Exercise5.question3();
// Exercise5.question4();
